export function isLoggedin(){
    return true
}

export function getJWT(){
    return "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQVJUSVNUIiwic3ViIjoiMzE4ODg2ODktMjA4ZS00Yjg5LWFhNTYtMjRlMDgxMzE2ZDQ3IiwiRW1haWwiOiJhcnRpc3RAZ21haWwuY29tIiwiZXhwIjoxNTkwMDY2MTc5fQ.SM-YbUviEJWWXV5dfwcx4UmR_vd0dDLILVmws__Y47HgsKO8r52oKSoj_Hw0ND8fQsoWNStgwp_FkzUuu94jwg"
}