export function isLoggedin(){
    return true
}

export function getJWT(){
    return "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQVJUSVNUIiwic3ViIjoiMzE4ODg2ODktMjA4ZS00Yjg5LWFhNTYtMjRlMDgxMzE2ZDQ3IiwiRW1haWwiOiJhcnRpc3RAZ21haWwuY29tIiwiZXhwIjoxNTg5MDI0NzM5fQ.yGnhDDuP08-SLVs0xVHOT90Xyj_gxp3otK7z1OghG6_QJJziQwhrItOlAAG1aEnwtye-5HIncLXT_OsqOsw9LA"
}